### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by mariospapaz** [mariospapaz/my-workout#1]
## Requirements
- [x] Make svelte attach from API
- [x] Get Tailwind CSS working

## Bugs
- [x] Update Go API to support AllowAllOrigin 
- [ ]  Tailwind button has centering issues

## Suggestions 
- [ ] Sets on a separate new line
- [ ] semi black-transparent background behind exercises
