### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by mariospapaz** [mariospapaz/my-workout#5]
- [x] Project Plan 📃 
- [x] Make the baby steps of `api.go` 
- [x] Get Go to connect with MongoDB
- [x] Insert `.mongo/data.json` to MongoDB
- [x] Make `/api/workouts` return the whole data.json
- [x] Make `/api/workout/:day` return a specific part of data.json
- [x] Optimize api.go and database.go
- [x] Improve JSON consistency
- [x] Remove hardcoded networking
- [x] Make a automation publishing script
- [x] Finish the Project
- [x] Publish the Image 🖼️

**Comment by mariospapaz** [comment]
It's been an interesting project with multiples trials and errors.
